# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-advance-options"
client_id = "66b7df45b4b7d570e453b6c19c84d024"
application_url = "https://magic-thereafter-machinery-goat.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts"

[auth]
redirect_urls = [
  "https://magic-thereafter-machinery-goat.trycloudflare.com/auth/callback",
  "https://magic-thereafter-machinery-goat.trycloudflare.com/auth/shopify/callback",
  "https://magic-thereafter-machinery-goat.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "developer-1001.myshopify.com"
