# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Advanced Options App"
client_id = "bea5a571c967a3e11260986287ff075d"
application_url = "https://dimensions-dow-equilibrium-reverse.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_discounts,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://dimensions-dow-equilibrium-reverse.trycloudflare.com/auth/callback",
  "https://dimensions-dow-equilibrium-reverse.trycloudflare.com/auth/shopify/callback",
  "https://dimensions-dow-equilibrium-reverse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appdev-101.myshopify.com"
